### ISSUE TITLE
[Bug] [Error: ENOENT: no such file or directory, scandir]

### ISSUE THREAD

**Issue by ioofy** [jonluca/vite-typescript-ssr-react#10]
Hello, i hope you are good. I want to try improve this project with research about ssr, I like this template

But got some issues when running the server or client. You can see at this screenshot

<img width="1680" alt="Screenshot 2022-08-08 at 11 10 54" src="https://user-images.githubusercontent.com/77242429/183337687-22e89c41-2e2d-46e2-896a-b1f4995bc15c.png">

How the solve this issue? I'm using node engine 14.17.0

**Comment by ioofy** [comment]
Seems like on vite configuration, isn't it?

**Comment by ioofy** [comment]
https://github.com/storybookjs/builder-vite/issues/452 i've got the reference from others

**Comment by ioofy** [comment]
And this one too https://github.com/vitejs/vite/issues/9113 related with vite 3

**Comment by jonluca** [comment]
Hello, you might not be on a version of node that's new enough. Can you try node 18?

**Comment by ioofy** [comment]
> Hello, you might not be on a version of node that's new enough. Can you try node 18?

yeah i can, yep that a first solution, but how about another solution that we dont want upgrade the versions about this?

**Comment by ioofy** [comment]
hmm, read a lot reference and mention about this issue on vite there are no solutions other upgrading the node version 

Some one tell this 

Vite uses node: import which is supported in v16.0.0+ and v14.18.0+. v15 does not support this.
https://nodejs.org/api/esm.html#node-imports

**Comment by ioofy** [comment]
Hello @jonluca

**Comment by ioofy** [comment]
oops sorry, my bad. just some typo in here
