### ISSUE TITLE
How to deploy this app with vercel or netlify configuration?

### ISSUE THREAD

**Issue by ioofy** [jonluca/vite-typescript-ssr-react#11]
Hello @jonluca Want to ask, how about deploying this app on vercel or netlify? i've deployed that but some file can't be read which is static files and entry-client.tsx file.

Could you help me please?

**Comment by jonluca** [comment]
<img width="992" alt="Screen Shot 2022-08-08 at 10 16 14 AM" src="https://user-images.githubusercontent.com/13029040/183439133-c87a6c8e-2961-4ca5-901f-9b957eb9b490.png">

You can technically deploy this with vercel, but it will just be for the UI. If you're using vercel, I'd recommend using nextjs and their inline APIs/lambdas, which are pretty nice.

This would be more for deploying on a bare metal server or to AWS. You'd really only roll your own SSR if you need fine grain control over document injection, metadata, etc.

**Comment by ioofy** [comment]
> <img alt="Screen Shot 2022-08-08 at 10 16 14 AM" width="992" src="https://user-images.githubusercontent.com/13029040/183439133-c87a6c8e-2961-4ca5-901f-9b957eb9b490.png">
> 
> You can technically deploy this with vercel, but it will just be for the UI. If you're using vercel, I'd recommend using nextjs and their inline APIs/lambdas, which are pretty nice.
> 
> This would be more for deploying on a bare metal server or to AWS. You'd really only roll your own SSR if you need fine grain control over document injection, metadata, etc.

Hii yea I know nextjs is best solutions. But this is for experimental with my API testing.. I actually say this project is good.. Thank you for replying ^^ I glad to hear
