### ISSUE TITLE
Question : Can i accesing token with cookie?

### ISSUE THREAD

**Issue by ioofy** [jonluca/vite-typescript-ssr-react#15]
Hello, i want to ask can i accesing cookie data in some page for example i want to check for cookie token and if exist you can stay and otherwise you will be redirected into login page. This like initialProps nextjs or serverSideProps

Or other i want to fetching data in server side?
Can you give me a example please?

**Comment by jonluca** [comment]
If it's purely a server side check on intitial page load then you can do the check in `server.ts` - on line 60, you chould check `req.cookies` and the corresponding path, and do any auth you need there. This is just a simple express server, so you can theoretically do whatever you'd like.

This isn't a replacement for nextjs. Truth be told you should probably just use nextjs - it's gotten to a fairly mature point, and a boilerplate like this is only interesting if you absolutely must have a stateful server, for some reason.
