### ISSUE TITLE
Update head tags using Helmet

### ISSUE THREAD

**Issue by tawn33y** [jonluca/vite-typescript-ssr-react#18]
I'm using [react-helmet](https://www.npmjs.com/package/react-helmet) to update the `Head` tags but the built HTML source (ctrl + u) does not reflect this. However, if you inspect element (ctrl + shift + i) and look at the source, the head is updated well.

```ts
// server.ts
// here we only update the html, not the head tags
const { render } = await vite.ssrLoadModule(isProd ? productionBuildPath : devBuildPath);
...
const html = template.replace(`<!--app-html-->`, appHtml)
```

Any ideas on how to update the head tags as well?

**Comment by jonluca** [comment]
https://github.com/nfl/react-helmet

You should check out that library. You basically have to statically render the head in that case, and add the replacement into the html. You could call `const head = Helmet.renderStatic()` and then do another `template.replace(``, head.title.toString())`, and add in `app-title` to `index.html`.

However I'd be wary of any of this - https://github.com/nfl/react-helmet/issues/216 - react helmet is inherently not thread safe, so you might run into data pollutions with this.
