### ISSUE TITLE
I meet a problem

### ISSUE THREAD

**Issue by ToWeLong** [jonluca/vite-typescript-ssr-react#2]
I want to use ssr but when I  send http request, then the page is not Rendering of my server datas, for example I send a request to get dog img  but page shows `<img  src=""/>`. I expect a result is `<img src="http://xxxx.jpg">`. So Can you provide a example?

**Comment by jonluca** [comment]
What's the issue? Are you populating the data for `src` in a `useEffect`? Most hooks only run after first render, which'll only be in the client

**Comment by ToWeLong** [comment]
> What's the issue? Are you populating the data for `src` in a `useEffect`? Most hooks only run after first render, which'll only be in the client

yeah, I tried to fetch data that it is like before in `useEffect `, but don't work in server render. So I want to get data before first render. What should I do?
